name: gen-ai-chatbot-template
description: ''
version: 0.1.0
author: maciej@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: genaichatbottemplate
  parentArtefactID: maciej_prophecy
  buildSystem: wheel
  author: null
  createdAt: '2023-06-13 00:50:07'
pipelines:
  pipelines/web_vectorize:
    name: web_vectorize
    description: ''
    author: maciej@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-06-13 02:05:35'
    datasets:
      inputs:
      - datasets/web_bronze_content
      - datasets/web_silver_content_vectorized
      outputs:
      - datasets/all_vectors_silver
      - datasets/web_silver_content_vectorized
    subgraphs: []
    dependencies: {}
  pipelines/chatbot_batch:
    name: chatbot_batch
    description: ''
    author: maciej@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-06-13 05:00:18'
    datasets:
      inputs:
      - datasets/question_seed
      - datasets/web_silver_content_vectorized
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/chatbot_live:
    name: chatbot_live
    description: ''
    author: maciej@prophecy.io
    mode: stream
    artefactID: ''
    language: python
    createdAt: '2023-06-22 05:25:43'
    datasets:
      inputs:
      - datasets/slack_chat
      - datasets/web_silver_content_vectorized
      outputs:
      - datasets/bot_messages_target
    subgraphs: []
    dependencies: {}
  pipelines/web_ingest:
    name: web_ingest
    description: ''
    author: maciej@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-06-22 05:27:53'
    datasets:
      inputs:
      - datasets/web_bronze_sitemap
      - datasets/web_bronze_url
      outputs:
      - datasets/web_bronze_content
      - datasets/web_bronze_sitemap_raw
    subgraphs: []
    dependencies: {}
datasets:
  datasets/web_bronze_sitemap_raw:
    name: web_bronze_sitemap_raw
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-13 01:53:47'
    mode: batch
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: File
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-13 01:53:47'
  datasets/web_bronze_sitemap:
    name: web_bronze_sitemap
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-13 01:56:28'
    mode: batch
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: File
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-13 01:56:28'
  datasets/web_bronze_content:
    name: web_bronze_content
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-13 02:01:38'
    mode: batch
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-13 02:01:38'
  datasets/web_silver_content_vectorized:
    name: web_silver_content_vectorized
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-13 04:20:06'
    mode: batch
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-13 04:20:06'
  datasets/all_vectors_silver:
    name: all_vectors_silver
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-13 04:38:14'
    mode: batch
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: Warehouse
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-13 04:38:15'
  datasets/question_seed:
    name: question_seed
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-13 05:18:30'
    mode: batch
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: File
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-13 05:18:30'
  datasets/slack_chat:
    name: slack_chat
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-20 04:50:15'
    mode: stream
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: WebApp
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-20 04:50:15'
  datasets/bot_messages_target:
    name: bot_messages_target
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-20 04:50:58'
    mode: stream
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: WebApp
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-20 04:50:58'
  datasets/web_bronze_url:
    name: web_bronze_url
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-24 20:23:30'
    mode: batch
    physicalDatasets:
      db_product:
        fabricId: 1777
        datasetType: WebApp
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-24 20:23:30'
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-06-13 00:50:07'
  gems: {}
  udfs:
    udfs/scrape_text:
      name: scrape_text
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: maciej@prophecy.io
      createdAt: '2022-12-15 18:04:50'
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: pypi
  id: KfvmV
  name: Prophecy Spark AI (Python)
  enabled: false
  package: prophecy-spark-ai==0.1.8
- type: coordinates
  coordinates: io.prophecy:spark-ai_2.12:0.1.8
  name: Prophecy Spark AI
  enabled: false
  id: xs0D8
  exclusions: []
projectDependencies: {}
pipelineConfigurations: {}
